### ISSUE TITLE
Your First Issue (Which is real)

### ISSUE THREAD

**Issue by wolfiepawz** [dylanhansch/CloudFlare-subdomain#1]
Hi!
This is your first issue (hurray?)

Okay, all jokes aside.

From one Minecrafter to another.
I have a small issue with the Cloudflare Subdomain script.

I have set up the script accordingly to what it needs (email and token and the domain).

When I fill in the fields, and hit "Create", it just sends me back to the same screen without and information what-so-ever. 
The subdomain is not created either.

I am really hoping for some help.

You can find me on Discord if you want:

https://discord.gg/PEMfq8K

**Comment by dylanhansch** [comment]
Closing because tool currently doesn't work. Will eventually fix it. Also see issue #3 .
